# LOG MESSAGE TEMPLATES
INFO = '\nINFO.\n--------------------------------------\nMESSAGE: {}\n'
SCANNER_INFO = '\nSCANNER INFO.\n--------------------------------------\nMESSAGE: {}\n'
RPC_PROVIDER_ERROR = '\nPRC PROVIDER ERROR.\n--------------------------------------\nMESSAGE: {}\n'
RPC_PROVIDER_INFO = '\nPRC PROVIDER INFO.\n--------------------------------------\nMESSAGE: {}\n'
NETWORK_ERROR = '\nNETWORK ERROR.\n--------------------------------------\nMESSAGE: {}\n'
CONTRACT_ERROR = '\nCONTRACT ERROR.\n--------------------------------------\nMESSAGE: {}\n'
CONTRACT_INFO = '\nCONTRACT INFO.\n--------------------------------------\nMESSAGE: {}\n'
SIGNER_INFO = '\nSIGNER INFO.\n--------------------------------------\nMESSAGE: {}\n'
SIGNER_ERROR = '\nSIGNER ERROR.\n--------------------------------------\nMESSAGE: {}\n'
TRADE_ERROR = '\nTRADE ERROR.\n--------------------------------------\nMESSAGE: {}\n'
TRADE_INFO = '\nTRADE INFO.\n--------------------------------------\nMESSAGE: {}\n'
TRANSACTION_ERROR = '\nTRANSACTION ERROR.\n--------------------------------------\nMESSAGE: {}\n'
TRANSACTION_WARNING = '\nTRANSACTION WARNING.\n--------------------------------------\nMESSAGE: {}\n'
TRANSACTION_INFO = '\nTRANSACTION INFO.\n--------------------------------------\nMESSAGE: {}\n'
TOKEN_ERROR = '\nTOKEN ERROR.\n--------------------------------------\nMESSAGE: {}\n'
UNEXPECTED_ERROR = '\nUNEXPECTED ERROR.\n--------------------------------------\nMESSAGE: {}\n'
REQUEST_ERROR = '\nREQUEST ERROR.\n--------------------------------------\nMESSAGE: {}'
REQUEST_INFO = '\nREQUEST INFO.\n--------------------------------------\nMESSAGE: {}'
RESPONSE_ERROR = '\nRESPONSE ERROR.\n--------------------------------------\nMESSAGE: {}'
RESPONSE_INFO = '\nRESPONSE INFO.\n--------------------------------------\nMESSAGE: {}'
###
